spring:
  application:
    name: Ecommerce_app
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: toor
  jpa:
    hibernate:
      ddl-auto: update




