spring:
  application:
    name: Ecommerce_app
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: toor
  jpa:
    hibernate:
      ddl-auto: update

encryption:
  salt:
    rounds: 10


jwt:
  algorithm:
    key: suberSecuredAlgorithmSecritKey
  issure: eCommerce
  expireInSeconds: 604800
